server:
  port: 9394
  servlet:
    context-path: /


spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/df?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: 1q2w3e

      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30000

  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    cache: false
    encoding: utf-8
  mvc:
    static-path-pattern: /static/**

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.liuwenxu.boot
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback-spring.xml
